✨ Input 컴포넌트 추가 #6
gdg-temp/client pull request #8
Opened 2023-08-30 16:38 UTC by hyunjin-C

# ✨ Input 컴포넌트 추가

### 작업 사항
![image](https://github.com/gdg-temp/client/assets/89180168/3d7af023-f389-4da4-8c94-287014971a72)
- Input 컴포넌트 추가

<br/>

### 참고 사항

- Input 컴포넌트의 props는 일단 임의로 설정해보았습니다. Input 컴포넌트의 사용 목적에 따라 변경될 수 있을 것 같아요.

<br/>

closed #6 

<br/>

2023-09-03 04:45 UTC, haesoo-y approved these changes
코드가 깔끔해서 잘읽혔습니다 ㅎㅎ
추후에 스타일 들어가면 수정하면 될 것 같아요 🤗

2023-09-03 09:51 UTC, haesoo-y commented on src/components/Input/index.tsx
> +};
스타일드컴포넌트로 통일하기로 해서 요것도 분리해야할것같아요.

2023-09-03 09:56 UTC, haesoo-y requested changes
분리필요

2023-09-04 09:40 UTC, hyunjin-C commented on src/components/Input/index.tsx
> +};
@haesoo-y Input.styled.ts 파일에 에러 컴포넌트 추가하면 될까요?

2023-09-05 13:34 UTC, haesoo-y approved these changes
수고하셨습니다~

2023-09-07 01:06 UTC, merged